name: publish to nuget
on:
  push:
    branches:
      - '*' # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Build the project
        run: dotnet build --configuration Release

      # Publish
      - name: Publish the package to nuget.org
        run: |
          for file in */bin/Release/*.nupkg; do
            dotnet nuget push "$file" -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
          done
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}