name: Build and Publish to NuGet

on:
  push:
    branches:
      - '**' # Run on push to any branch

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build_artifacts
          path: 'HP.CloudApi.Client/bin/Release/*.nupkg'

  publish:
    name: Publish to NuGet
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref_name == 'master' }}
    steps:
      - uses: actions/checkout@v5

      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: build_artifacts
          path: build_artifacts

      - name: List artifact files
        run: ls -R build_artifacts

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Publish the package to nuget.org
        run: |
          for file in build_artifacts/*.nupkg; do
            dotnet nuget push "$file" -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json --skip-duplicate
          done
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
